trigger:
  branches:
    include:
    - dev
    - release-*
    - refs/tags/*
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
stages:
  - stage: CI
    condition: not(or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), contains(variables['Build.SourceBranchName'], 'release-')))
    jobs:
    - job: Windows
      strategy:
        matrix:
          VS2017:
            imageName: 'vs2017-win2016'
            TILEDB_S3: ON
      pool:
        vmImage: $(imageName)
      steps:
      - template: scripts/azure-windows.yml

  - stage: Build_Release
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')
    variables:
      TILEDB_S3: ON
      TILEDB_AZURE: ON
      TILEDB_GCS: ON
      TILEDB_HDFS: ON
      TILEDB_STATIC: OFF
      TILEDB_SERIALIZATION: ON
      TILEDB_FORCE_BUILD_DEPS: ON
      MACOSX_DEPLOYMENT_TARGET: 10.9
    jobs:
     - job:
       strategy:
         matrix:
           linux:
             imageName: 'ubuntu-16.04'
             CXX: g++
             ARTIFACT_OS: 'linux'
           macOS:
             imageName: 'macOS-10.14'
             CXX: clang++
             ARTIFACT_OS: 'macos'
       pool:
         vmImage: $(imageName)
       steps:
         - template: scripts/azure-linux_mac-release.yml

     - job: Windows
       strategy:
         matrix:
           VS2017:
             imageName: 'vs2017-win2016'
             # Only S3 variable is currently supported in boostrap powershell
             TILEDB_S3: ON
#             TILEDB_AZURE: OFF
#             TILEDB_GCS: OFF
#             TILEDB_HDFS: OFF
             TILEDB_STATIC: OFF
#             TILEDB_SERIALIZATION: OFF
             TILEDB_FORCE_BUILD_DEPS: ON
             ARTIFACT_OS: 'windows'
       pool:
         vmImage: $(imageName)
       steps:
         - template: scripts/azure-windows-release.yml

